apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-todo-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.port }}